-- MySQL Script generated by MySQL Workbench
-- 09/12/19 16:25:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema estoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estoque` DEFAULT CHARACTER SET utf8 ;
USE `estoque` ;

-- -----------------------------------------------------
-- Table `estoque`.`caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`caixa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `valorDeEntra` DOUBLE NULL DEFAULT NULL,
  `valorDeSaida` DOUBLE NULL DEFAULT NULL,
  `dataMovimento` DATE NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`categoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Categoria` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`dado_bancario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`dado_bancario` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `banco` VARCHAR(30) NULL DEFAULT NULL,
  `tpConta` VARCHAR(30) NULL DEFAULT NULL,
  `agencia` VARCHAR(30) NULL DEFAULT NULL,
  `operacao` VARCHAR(30) NULL DEFAULT NULL,
  `conta` VARCHAR(40) NULL DEFAULT NULL,
  `pessoa_juridica_id` INT(11) NULL DEFAULT NULL,
  `pessoa_fisica_id` INT(11) NULL DEFAULT NULL,
  `tipoPessoa` INT(11) NULL DEFAULT NULL,
  `tpFornecedorCliente` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`dado_complementar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`dado_complementar` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(60) NULL DEFAULT NULL,
  `celular` VARCHAR(60) NULL DEFAULT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `observacao` VARCHAR(3000) NULL DEFAULT NULL,
  `pessoa_juridica_id` INT(11) NULL DEFAULT NULL,
  `pessoa_fisica_id` INT(11) NULL DEFAULT NULL,
  `tipoPessoa` INT(11) NULL DEFAULT NULL,
  `tpFornecedorCliente` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`endereco` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `logradouro` VARCHAR(50) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `uf` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `pessoa_juridica_id` INT(11) NULL DEFAULT NULL,
  `pessoa_fisica_id` INT(11) NULL DEFAULT NULL,
  `tipoPessoa` INT(11) NULL DEFAULT NULL,
  `tpFornecedorCliente` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`produto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(150) NULL DEFAULT NULL,
  `unidade` VARCHAR(45) NULL DEFAULT NULL,
  `codigoBarra` VARCHAR(45) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `minimo_estoque` DOUBLE NULL DEFAULT NULL,
  `apresentacao` VARCHAR(45) NULL DEFAULT NULL,
  `categoria_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `categoria_id`),
  INDEX `fk_produto_categoria1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `estoque`.`categoria` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`entrada_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`entrada_estoque` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `lote` VARCHAR(45) NULL DEFAULT NULL,
  `data_vencimento` DATE NULL DEFAULT NULL,
  `numero_calcado` VARCHAR(45) NULL DEFAULT NULL,
  `preco_custo` DOUBLE NULL DEFAULT NULL,
  `margem_venda` DOUBLE NULL DEFAULT NULL,
  `quantidade` DOUBLE NULL DEFAULT NULL,
  `preco_venda` DOUBLE NULL DEFAULT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  `produto_id` INT(11) NOT NULL,
  `categoria_id` INT(11) NOT NULL,
  `fornecedor_pf` INT(11) NULL DEFAULT NULL,
  `fornecedor_pj` INT(11) NULL DEFAULT NULL,
  `codigoBarra` VARCHAR(45) NULL DEFAULT NULL,
  `num_nota_fiscal` VARCHAR(30) NULL DEFAULT NULL,
  `data_nota_fiscal` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `produto_id`, `categoria_id`),
  INDEX `fk_entrada_estoque_produto_idx` (`produto_id` ASC),
  INDEX `fk_entrada_estoque_categoria1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_entrada_estoque_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `estoque`.`categoria` (`id`),
  CONSTRAINT `fk_entrada_estoque_produto`
    FOREIGN KEY (`produto_id`)
    REFERENCES `estoque`.`produto` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`extrato_conta_emhaver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`extrato_conta_emhaver` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cliente_pf` INT(11) NULL DEFAULT NULL,
  `cliente_pj` INT(11) NULL DEFAULT NULL,
  `valor_conta` DOUBLE NULL DEFAULT NULL,
  `valor_pago` DOUBLE NULL DEFAULT NULL,
  `lancamento_em_haver_venda_id` INT(11) NULL DEFAULT NULL,
  `num_venda` INT(11) NULL DEFAULT NULL,
  `data_movimento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`lancamento_em_haver_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`lancamento_em_haver_venda` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cliente_pf` INT(11) NULL DEFAULT NULL,
  `cliente_pj` INT(11) NULL DEFAULT NULL,
  `num_venda` DOUBLE NULL DEFAULT NULL,
  `valor_em_haver_compra` DOUBLE NULL DEFAULT NULL,
  `statusDaConta` INT(11) NULL DEFAULT NULL,
  `data_lancamento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`pagamento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `num_venda` INT(11) NULL DEFAULT NULL,
  `forma_pagamento` INT(11) NULL DEFAULT NULL,
  `valor_por_formaPgamento` DOUBLE NULL DEFAULT NULL,
  `total_venda` DOUBLE NULL DEFAULT NULL,
  `cliente_pf` INT(11) NULL DEFAULT NULL,
  `cliente_pj` INT(11) NULL DEFAULT NULL,
  `statusPagamento` INT(11) NULL DEFAULT NULL,
  `dataVenda` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8
COMMENT = '	';


-- -----------------------------------------------------
-- Table `estoque`.`pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`pessoa_fisica` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `rg` VARCHAR(30) NULL DEFAULT NULL,
  `orgaoExpedidor` VARCHAR(10) NULL DEFAULT NULL,
  `dataExpedicao` DATE NULL DEFAULT NULL,
  `ufExpedicao` VARCHAR(10) NULL DEFAULT NULL,
  `dataNascimento` DATE NULL DEFAULT NULL,
  `nomeMae` VARCHAR(45) NULL DEFAULT NULL,
  `estadoCivil` VARCHAR(30) NULL DEFAULT NULL,
  `tpFornecedorCliente` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`pessoa_juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`pessoa_juridica` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(18) NULL DEFAULT NULL,
  `abertura` DATE NULL DEFAULT NULL,
  `nomeEmpresarial` VARCHAR(45) NULL DEFAULT NULL,
  `tituloEstabelecimento` VARCHAR(45) NULL DEFAULT NULL,
  `inscricaoMunicipal` VARCHAR(45) NULL DEFAULT NULL,
  `inscricaoEstadual` VARCHAR(45) NULL DEFAULT NULL,
  `tpFornecedorCliente` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`saida_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`saida_venda` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigoBarra` VARCHAR(45) NULL DEFAULT NULL,
  `produto_id` INT(11) NOT NULL,
  `unidade` VARCHAR(45) NULL DEFAULT NULL,
  `preco_unitario` DOUBLE NULL DEFAULT NULL,
  `quantidade_venda` DOUBLE NULL DEFAULT NULL,
  `desconto` DOUBLE NULL DEFAULT NULL,
  `total_por_produto` DOUBLE NULL DEFAULT NULL,
  `data_hora_venda` DATE NULL DEFAULT NULL,
  `num_venda` INT(11) NULL DEFAULT NULL,
  `item_venda_produto` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `produto_id`),
  INDEX `fk_saida_venda_produto1` (`produto_id` ASC),
  CONSTRAINT `fk_saida_venda_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `estoque`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`total_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`total_produto` (
  `produto_id` INT(11) NOT NULL,
  `codigoBarra` VARCHAR(45) NULL DEFAULT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`produto_id`),
  CONSTRAINT `fk_total_produto_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `estoque`.`produto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
